name: Lint and Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install bandit pip-audit

      - name: Run formatting and lint checks
        run: |
          python -m compileall src

      - name: Run bandit (report only)
        continue-on-error: true
        run: |
          bandit -r src/leetcode_solutions || true

      - name: Run pip-audit (report only)
        continue-on-error: true
        run: |
          pip-audit || true

      - name: Summarize results
        run: |
          echo "Quality checks completed. Review logs for warnings."
